puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/index.html'), name='logout'),
    path('settings/', views.settings, name='settings'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:pk>/', views.profile, name='profile')
]

puddle/item/urls.py
from django.urls import path

from . import views
from .views import(
    OrderSummaryView
)

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<int:pk>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from core.views import index

urlpatterns = [
    path("", include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('payment/',include('payment.urls')),
    path('rating/', include('rating.urls')),
    path('searchbyimage/', include('searchbyimage.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from decimal import ROUND_DOWN, Decimal
from django.db import models
from django.contrib.auth import get_user_model
from rating.models import Rating

User = get_user_model()

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    bio = models.TextField(blank=True)
    profileimg = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    location = models.CharField(max_length=100, blank=True)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)

    def __str__(self):
        return self.user.username
    
    def calculate_avg_rating(self):
        ratings = Rating.objects.filter(item__created_by=self.user)
        if ratings.count() > 0:
            sum_ratings = sum([rating.rating for rating in ratings])
            avg_rating = Decimal(sum_ratings) / ratings.count()
            self.average_rating = avg_rating.quantize(Decimal('0.00'), rounding=ROUND_DOWN)
        else:
            self.average_rating = 0
        self.save()
    

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'You username',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'You password',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email', 'password1','password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'You username',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'You email',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'You password',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0'
    }))

class SettingProfileForm(forms.ModelForm):
    firstname = forms.CharField(max_length=30, required=True)
    lastname = forms.CharField(max_length=30, required=True)
    class Meta:
        model = Profile
        fields = ('profileimg','firstname', 'lastname','bio','location')
        widgets = {
            'profileimg': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'firstname': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'lastname': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'bio': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'location': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            
            
        }
    def save(self, commit=True):
        profile = super(SettingProfileForm, self).save(commit=False)
        user = profile.user
        user.first_name = self.cleaned_data['firstname']
        user.last_name = self.cleaned_data['lastname']
        if commit:
            profile.save()
            user.save()
        return profile
    
class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('old_password','new_password1', 'new_password2')
    
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Old password',
        'class': 'peer block min-h-[auto] w-full rounded border border-gray-300 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 focus:bg-white hover:bg-white dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" type="text" placeholder="Nhập nội dung ở đây"'
    }))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'You password',
        'class': 'peer block min-h-[auto] w-full rounded border border-gray-300 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 focus:bg-white hover:bg-white dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" type="text" placeholder="Nhập nội dung ở đây"'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'peer block min-h-[auto] w-full rounded border border-gray-300 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 focus:bg-white hover:bg-white dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" type="text" placeholder="Nhập nội dung ở đây"'
    }))

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm, SettingProfileForm, ChangePasswordForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User, auth
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    item_list = Item.objects.filter(is_sold=False).order_by('-id')
    paginator = Paginator(item_list, 16)  # Chia các mục thành các trang chứa tối đa 8 mục.

    page = request.GET.get('page')  # Lấy số trang từ tham số truy vấn.
    items = paginator.get_page(page)  # Lấy các mục cho trang hiện tại.

    categories = Category.objects.all()

    numbers = [0.5,1.5,2.5,3.5,4.5]

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'numbers': numbers,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user_login = auth.authenticate(username=username, password=password)
            auth.login(request, user_login)

            user_model = User.objects.get(username=username)
            new_profile = Profile.objects.create(user=user_model, id_user=user_model.id)
            new_profile.save()

            return redirect('/settings/')
 
        
    else:
        form = SignupForm()

    return render(request, 'core/signup.html',{
        'form' : form
    })

@login_required
def settings(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = SettingProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('core:profile', pk=request.user.username)
    else:
        form = SettingProfileForm(instance=profile, initial={
            'firstname': request.user.first_name,
            'lastname': request.user.last_name,
        })
    return render(request, 'core/setting.html', {'form': form})

@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user)
            return redirect('core:index')
    else:
        form = ChangePasswordForm(request.user)
    return render(request,'core/changepassword.html',{
        'form':form 
    })

@login_required
def profile(request, pk):
    user_object= User.objects.get(username=pk)
    user_profile = Profile.objects.get(user=user_object)
    user_profile.calculate_avg_rating()
    user_items = Item.objects.filter(created_by=user_object)
    user_items_length = len(user_items)

    numbers = [0.5,1.5,2.5,3.5,4.5]
    
    context = {
        'user_object' : user_object,
        'user_profile' : user_profile,
        'user_items': user_items,
        'user_items_length' :user_items_length,
        'numbers':numbers,
    }
    return render(request, 'core/profile.html', context)

    

puddle/core/templates/core/changepassword.html
{% extends 'core/base.html' %}

{%block title%} Change Password {%endblock%}

{%block content%}
    <div class="w-1/2 my-0 ml-80 p-0 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Change Password </h1>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label  class="inline-block mb-2">Old Password</label><br>
                {{ form.old_password }}
            </div>
            <div class="mb-3">
                <label  class="inline-block mb-2">New Password</label><br>
                {{ form.new_password1 }}
            </div>
            <div class="mb-3">
                <label  class="inline-block mb-2">Repeat New Password</label><br>
                {{ form.new_password2 }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-300 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-orange-500 hover:bg-orange-700 rounded-xl text-white">Submit</button>

        </form>
    </div>
{%endblock%}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{%block title%}
Wecomle
{%endblock%}

{% block content %}
<script>
    window.addEventListener('scroll', function() {
        localStorage.setItem('scrollPosition', window.pageYOffset-200);
    });
    window.addEventListener('load', function() {
        var scrollPosition = localStorage.getItem('scrollPosition');
        if (scrollPosition !== null) {
            window.scrollTo(0, scrollPosition);
            localStorage.removeItem('scrollPosition');
        }
    });
    
  </script>
{% comment %} 
    <div class="px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-10 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="object-cover h-72 w-90">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{%url 'item:items'%}?category={{category.id}}">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div> {% endcomment %}
    <div class="container mx-auto px-6">
        <div class="h-64 rounded-md overflow-hidden bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')">
            <div class="bg-gray-900 bg-opacity-50 flex items-center h-full">
                <div class="px-10 max-w-xl">
                    <h2 class="text-2xl text-white font-semibold">Clothing</h2>
                    <p class="mt-2 text-gray-400">Hãy trang bị cho mình những bộ trang phục đẹp và thoải mái nhất với các sản phẩm áo quần chất lượng cao của chúng tôi! Hãy đến và khám phá bộ sưu tập đa dạng của chúng tôi để tìm ra những chiếc áo quần phù hợp với phong cách và sở thích của bạn ngay hôm nay.</p>
                    <a href="{%url 'item:items'%}?category=2" class="flex items-center mt-4 px-3 py-2 bg-orange-600 text-white text-sm uppercase font-medium rounded hover:bg-orange-500 focus:outline-none focus:bg-blue-500">
                        <span>Shop Now</span>
                        <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                    </a>
                </div>
            </div>
        </div>
        <div class="md:flex mt-8 md:-mx-4">
            <div class="w-full h-64 md:mx-4 rounded-md overflow-hidden bg-cover bg-center md:w-1/2" style="background-image: url('https://images.unsplash.com/photo-1674448417295-088682b6adec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80')">
                <div class="bg-gray-900 bg-opacity-50 flex items-center h-full">
                    <div class="px-10 max-w-xl">
                        <h2 class="text-2xl text-white font-semibold">Toys</h2>
                        <p class="mt-2 text-gray-400">Chào mừng bạn đến với cửa hàng đồ chơi của chúng tôi! Hãy đến và khám phá những sản phẩm đa dạng và thú vị để mang lại niềm vui cho bạn và gia đình ngay hôm nay.</p>
                        <a href="{%url 'item:items'%}?category=1" class="flex items-center mt-4 text-white text-sm uppercase font-medium rounded hover:underline focus:outline-none">
                            <span>Shop Now</span>
                            <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="w-full h-64 mt-8 md:mx-4 rounded-md overflow-hidden bg-cover bg-center md:mt-0 md:w-1/2" style="background-image: url('https://images.unsplash.com/photo-1450778869180-41d0601e046e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1886&q=80')">
                <div class="bg-gray-900 bg-opacity-50 flex items-center h-full">
                    <div class="px-10 max-w-xl">
                        <h2 class="text-2xl text-white font-semibold">Pets</h2>
                        <p class="mt-2 text-gray-400">Chúng tôi có những chú cún, mèo và các loại thú cưng khác đáng yêu và khỏe mạnh, sẵn sàng trở thành bạn đồng hành đáng tin cậy của bạn. Hãy đến và tìm cho mình một người bạn đáng yêu và trung thành ngay hôm nay.</p>
                        <a href="{%url 'item:items'%}?category=3" class="flex items-center mt-4 text-white text-sm uppercase font-medium rounded hover:underline focus:outline-none">
                            <span>Shop Now</span>
                            <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mx-auto px-6 my-8">
            <h3 class="text-gray-700 text-2xl font-medium">Newest Items</h3>
            <span class="mt-3 text-sm text-gray-500">200+ Products</span>
            <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-6">
                {% for item in items %}
                    <div class="w-full border border-orange-600 max-w-sm mx-auto rounded-lg shadow-md overflow-hidden">
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="flex items-end justify-end h-56 w-full bg-cover" style="background-image: url('{{item.image.url}}')">
                                    <button href="{{ item.get_add_to_cart_url }}" class="p-2 rounded-full bg-orange-600 text-white mx-5 -mb-4 hover:bg-blue-500 focus:outline-none focus:bg-blue-500">
                                        <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                                    </button>
                            </div>
                            <div class="px-5 py-3">
                                <h3 class="text-gray-700 uppercase">{{item.name}}</h3>
                                {% if item.discount_price %}
                                    <span class="text-gray-500 mt-2">{{item.discount_price}}</span>
                                {% else %}
                                    <span class="text-gray-500 mt-2">{{item.price}}</span>
                                {% endif %}                       
                                <h4 class="font-bold text-slate-700">{{item.created_by.first_name}}</h4>
                                <!-- Rating -->
                                <span class="flex items-center gap-4 text-sm rounded text-slate-500">
                                    <span class="flex gap-1 text-amber-400" role="img" aria-label="Rating: 4 out of 5 stars">
                                    {% for i in numbers %}
                                        {% if i <= item.average_rating %}
                                        <span aria-hidden="true">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                                            <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                                            </svg>
                                        </span>
                                        {% else %}
                                        <span aria-hidden="true">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                                            </svg>
                                        </span>
                                        {% endif %}
                                    {% endfor %}
                                        </span>
                                        <span> {{item.average_rating}} out 5</span>
                                    </span>
                            </div>
                            
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="flex justify-center">
                <div class="flex rounded-md mt-8">
                    {% if items.has_previous %}
                        <a href="?page={{ items.previous_page_number }}" class="py-2 px-4 leading-tight bg-white border border-gray-200 text-orange-600 border-r-0 ml-0 rounded-l hover:bg-orange-500 hover:text-white"><span>Previous</a>
                    {% endif %}
                    
                    {% for i in items.paginator.page_range %}
                        {% if items.number == i %}
                            <a href="#" class="py-2 px-4 leading-tight bg-white border border-gray-200 text-orange-600 border-r-0 hover:bg-orange-500 hover:text-white"><span>{{ i }}</span></a>
                        {% elif i > items.number|add:'-3' and i < items.number|add:'3' %}
                            <a href="?page={{ i }}" class="py-2 px-4 leading-tight bg-white border border-gray-200 text-orange-600 border-r-0 hover:bg-orange-500 hover:text-white"><span>{{ i }}</span></a>
                        {% endif %}
                    {% endfor %}
                    
                    {% if items.has_next %}
                        <a href="?page={{ items.next_page_number }}" class="py-2 px-4 leading-tight bg-white border border-gray-200 text-orange-600 rounded-r hover:bg-orange-500 hover:text-white"><span>Next</span></a>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}

puddle/core/templates/core/setting.html
{% extends 'core/base.html' %}

{% block title %}Setting Profile{% endblock title %}

{% block content%}
<h1 class="mb-4 text-3xl">{{title}}</h1>

<div class="flex justify-center border rounded-xl bg-white">
    <form method="post" action="." enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="space-y-4">
            {{form.as_p}}
            <img id="preview-image" src="#" alt="Preview" style="display: none; ">
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-300 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{form.non_field_errors}}
        </div>
        {% endif %}
        
        <button class="py-4 px-8 my-4 text-lg bg-orange-500 hover:bg-orange-700 rounded-xl text-white">Submit</button>
    </form>
</div>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('preview-image');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }

    document.getElementById('id_image').addEventListener('change', previewImage);
</script>
{%endblock%}