puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/index.html'), name='logout'),
    path('settings/', views.settings, name='settings'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:pk>/', views.profile, name='profile')
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from core.views import index

urlpatterns = [
    path("", include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('payment/',include('payment.urls')),
    path('rating/', include('rating.urls')),
    path('searchbyimage/', include('searchbyimage.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/rating/urls.py
from django.urls import path
from . import views

app_name = 'rating'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:order_item_id>/', views.rating, name='rating'),
]

puddle/rating/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Item, OrderItem
from django.core.validators import MaxValueValidator, MinValueValidator


class Rating(models.Model):
    user = models.ForeignKey(User, related_name='user_rating', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='item_rating', on_delete=models.CASCADE)
    order_item = models.ForeignKey(OrderItem, related_name='oder_item_rating', on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    rating_comment = models.TextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.item.name} - {self.rating} stars"

puddle/rating/forms.py
from django import forms
from .models import Rating

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('rating', 'rating_comment')
        widgets = {
            'rating_comment': forms.Textarea(attrs={'rows': 4})
        }

puddle/rating/views.py
from pyexpat.errors import messages
from django.http import Http404
from django.shortcuts import render
from  .models import Rating
from .forms import RatingForm
from item.models import Item, OrderItem
from .models import Rating
from core.models import Profile
from django.shortcuts import render,redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
# def rating(request):
#     return render(request, 'rating/rating.html')
@login_required
def index(request):
    rated_type = request.GET.get('rated_type', 0)
    if int(rated_type)==0:
        items = OrderItem.objects.filter(user=request.user,ordered=True, rated=False).order_by('-id')
    else:
        items = OrderItem.objects.filter(user=request.user,ordered=True, rated=True).order_by('-id')
    items_with_rating = []
    for item in items:
        rating = Rating.objects.filter(order_item=item).first()
        items_with_rating.append({
            'item': item,
            'rating': rating if rating else None,
        })

    return render(request, 'rating/index.html', {
        'items_with_rating':items_with_rating,
        'rated_type':rated_type,
    })

@login_required
def rating(request, order_item_id):
    order_item = get_object_or_404(OrderItem, id = order_item_id)
    item = order_item.item
    if order_item.rated==False:
        user = request.user
        profile = Profile.objects.get(user=user)
        if request.method == 'POST':
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.item = item
                rating.user = user
                rating.order_item = order_item
                rating.save()
                order_item.rated=True
                order_item.save()
                # update the average rating of the item, user
                item.calculate_avg_rating()
                profile.calculate_avg_rating()

                url = reverse('rating:index')
                url_with_params = url + '?rated_type=0'
                return redirect(url_with_params)
        else:
            form = RatingForm()

        numbers = [0.5,1.5,2.5,3.5,4.5]
        return render(request, 'rating/rating.html', {
            'form': form,
            'order_item' : order_item,
            'numbers':numbers,
            })
    else:
         return redirect('item:detail', pk=item.pk)

puddle/rating/templates/rating/index.html
{% extends 'core/base.html' %}

{% block title %}Rating Page {% endblock title %} 

{%block content%}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class='col-span-1 ml-6'>
        <p class="font-semibold mb-2">Rating page</p>
        <ul>          
             <a href="{%url 'rating:index'%}?rated_type=0">
                <li class="px-4 py-2 w-full border transition duration-200 ease-in-out hover:shadow-md hover:bg-white hover:text-gray-700 {% if rated_type == '0' %} bg-orange-600 text-cyan-500 font-semibold {% endif %}">{% comment %} {% if category.id == category_id %} bg-gray-200 text-cyan-500 font-semibold {% endif %} {% endcomment %}
                    Chưa đánh giá
                </li>
              </a>
              <a href="{%url 'rating:index'%}?rated_type=1">
                <li class="px-4 py-2 w-full border transition duration-200 ease-in-out hover:shadow-md hover:bg-white hover:text-gray-700 {% if rated_type == '1' %} bg-orange-600 text-cyan-500 font-semibold {% endif %}">
                   Đã đánh giá
               </li>
             </a>
        </ul>
    </div>
    <div class='col-span-3'>
        <div class="flex flex-col overflow-x-auto  border-t-2 border-orange-600 mt-4">
            <div class="sm:-mx-6 lg:-mx-8">
              <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
                <div class="overflow-x-auto">
                  <table class="min-w-full text-center text-sm font-light">
                    <thead class="border-b font-medium dark:border-neutral-500">
                      <tr>
                        <th scope="col" class="px-6 py-4 text-xl">Item Name</th>
                        <th scope="col" class="px-6 py-4 text-xl">Price</th>
                        <th scope="col" class="px-6 py-4 text-xl">Quantity</th>
                        <th scope="col" class="px-6 py-4 text-xl">Total Item Price</th>
                        <th scope="col" class="px-6 py-4 text-xl">Rate</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for item in items_with_rating %}
                            <tr class="border-b dark:border-neutral-500">
                                <td class="whitespace-nowrap px-6 py-4">{{item.item.item.name}}</td>
                                <td class="whitespace-nowrap px-6 py-4">{{item.item.item.price}}</td>
                                <td class="whitespace-nowrap px-6 py-4">
                                    {{item.item.quantity}}
                                </td>
                                <td class="whitespace-nowrap px-6 py-4">
                                    {% if item.item.discount_price %}
                                        ${{ item.item.get_total_discount_item_price }}
                                        <span class="badge badge-primary">Saving ${{ item.get_amount_saved }}</span>
                                    {% else %}
                                        ${{ item.item.get_total_item_price }}
                                    {% endif %}
                                </td>
                                <td class="whitespace-nowrap px-6 py-4">
                                    {% if rated_type == '0' %}
                                        <a href="{%url 'rating:rating'  item.item.id%}" class="bg-orange-600 hover:bg-orange-300 px-6 py-3 rounded-xl text-white">Rating</a>
                                    {% else %}
                                    <div>
                                      <p>{{item.rating.rating}} ★</p>
                                    </div>
                                    {% endif %}
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan='5'>Empty</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>
{% endblock %}

puddle/rating/templates/rating/rating.html
{% extends 'core/base.html' %}

{% block title %}Rating{% endblock title %}

{% block content %}
  <div class="flex flex-col md:flex-row">
    <div class="md:w-2/3 md:items-center ml-8 w-2/3 mx-auto flex justify-center items-center">
      <div class="md:w- lg:h-96 flex justify-center items-center bg-gray-100">
          <img class="rounded-xl object-cover h-full" src="{{order_item.item.image.url}}" alt="{{order_item.item.name}}">
      </div>
      <div class="w-full max-w-lg mx-auto mt-5 md:ml-8 md:mt-0 md:w-1/2">
          <h3 class="text-gray-700 uppercase text-lg">{{item.name}}</h3>
          {% if order_item.item.discount_price %}
              <span class="text-gray-500 mt-2 mr-2 text-red-500"><del>{{order_item.item.price}}</del></span>
              <span class="text-gray-500 mt-2">{{order_item.item.discount_price}}</span>
          {% else %}
              <span class="text-gray-500 mt-2">{{order_item.item.price}}</span>
          {% endif %}
          <p class="text-gray-500"><strong>Seller: </strong> <a href="{% url 'core:profile' order_item.item.created_by.username %}" class="text-decoration-line: underline">{{order_item.item.created_by.username}}</a> </p>
          {%if order_item.item.description%}
              <p class="text-gray-500"><strong>Description: </strong> {{order_item.item.description}} </p>
          {% endif %}
          <!-- Rating -->
          <span class="flex items-center gap-4 text-sm rounded text-slate-500">
            <span class="flex gap-1 text-amber-400" role="img" aria-label="Rating: 4 out of 5 stars">
            {% for i in numbers %}
                {% if i <= order_item.item.average_rating %}
                <span aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                    </svg>
                </span>
                {% else %}
                <span aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                    </svg>
                </span>
                {% endif %}
            {% endfor %}
                </span>
                <span> {{order_item.item.average_rating}} out 5</span>
            </span>
          <hr class="my-3">
          
      </div>
    </div>
    <div class="md:w-1/3 md:pl-4">
      <h1 class="text-2xl font-bold mb-4">Create rating for {{ order_item.item.name }}</h1>
      <form method="post">
        {% csrf_token %}
        <div class="mb-4">
          <label class="block font-bold text-gray-700 mb-2" for="{{ form.rating.id_for_label }}">Rating:</label>
          <input class="form-input w-2/3 rounded-md border-gray-300" type="number" id="{{ form.rating.id_for_label }}"
                 name="{{ form.rating.name }}" value="{{ form.rating.value|default:'5' }}"
                 min="1" max="5" required>
        </div>
        <div class="mb-4">
          <label class="block font-bold text-gray-700 mb-2" for="{{ form.comment.id_for_label }}">Comment:</label>
          {{ form.rating_comment }}
        </div>
        <button class="bg-orange-500 hover:bg-orange-600 text-white font-bold py-2 px-4 rounded"
                type="submit">Submit</button>
      </form>
  </div>
{% endblock content %}