puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/index.html'), name='logout'),
    path('settings/', views.settings, name='settings'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:pk>/', views.profile, name='profile')
]

puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name="dashboard"

urlpatterns = [
    path('', views.index, name="index"),
    path('sales_orders/', views.sales_orders, name='sales_orders'),
    path('purchase_orders/', views.purchase_orders, name='purchase_orders'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from core.views import index

urlpatterns = [
    path("", include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('payment/',include('payment.urls')),
    path('rating/', include('rating.urls')),
    path('searchbyimage/', include('searchbyimage.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from payment.models import ShippingAddress
from django.utils import timezone
from django.db.models import Sum


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_add_to_cart_url(self):
        return reverse("item:add-to-cart", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("item:remove-from-cart", kwargs={
            'pk': self.pk
        })
    def get_orderitem_quantity(self):
        total_quantity = OrderItem.objects.filter(item_id=self.id, ordered=True).aggregate(Sum('quantity'))['quantity__sum']
        return total_quantity if total_quantity else 0
    
    def calculate_avg_rating(self):
        from rating.models import Rating
        ratings = Rating.objects.filter(item=self)
        if ratings.count() > 0:
            sum_ratings = sum([rating.rating for rating in ratings])
            self.average_rating = sum_ratings / ratings.count()
        else:
            self.average_rating = 0
        self.save()
    
    
class OrderItem(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    rated = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    


class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def __init__(self, *args, **kwargs):
        ordered_date = kwargs.pop('ordered_date', None)
        super().__init__(*args, **kwargs)
        self.ordered_date = ordered_date
        self.save()

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total
    
    def complete_order(self):
        # Set ordered to True for all order items in this order
        for item in self.items.all():
            item.ordered = True
            item.save()
        self.ordered = True
        self.ordered_date = timezone.now()
        self.save()


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

puddle/dashboard/views.py
from collections import defaultdict
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models import Prefetch
from datetime import datetime, timedelta
from django.db.models import Sum, FloatField, F
from django.db.models.functions import Coalesce, Cast

# Create your views here.
from item.models import Item, Order, OrderItem

@login_required
def index(request):
    today = datetime.now().date()
    ten_days_ago = today - timedelta(days=9)  # Lấy 10 ngày gần nhất

    income_list = OrderItem.objects.filter(
        ordered=True,
        order__ordered_date__date__range=[ten_days_ago, today],
        user=request.user  # Lọc theo người dùng hiện tại
    ).values('order__ordered_date__date').annotate(
        total_income=Coalesce(
            Sum(F('quantity') * F('item__price'), output_field=FloatField()),
            0.0
        )
    ).order_by('order__ordered_date__date')

    date_income_list = []
    for income in income_list:
        date = income['order__ordered_date__date']
        total_income = income['total_income']
        date_income_list.append({'date': date, 'total_income': total_income})

    # Xác định các ngày không có dữ liệu và đặt giá trị thu nhập là 0
    date_range = [ten_days_ago + timedelta(days=i) for i in range(10)]
    for date in date_range:
        if date not in [income['date'] for income in date_income_list]:
            date_income_list.append({'date': date, 'total_income': 0.0})

    # Sắp xếp theo ngày
    date_income_list.sort(key=lambda x: x['date'])

    for date in date_income_list:
        print(date)
    #danh sách sản phẩm bán được
    items = Item.objects.filter(created_by=request.user).annotate(quantity_sold=models.Sum(models.Case(models.When(orderitem__ordered=True, then=models.F('orderitem__quantity')), default=0, output_field=models.IntegerField()))).order_by('-quantity_sold')[:6]
    item_quantity_list = [(item, item.quantity_sold) for item in items]
    context = {
        'date_income_list': date_income_list,
        'item_quantity_list': item_quantity_list
    }
    return render(request, 'dashboard/index.html', context)

@login_required
def purchase_orders(request):
    purchase_orders = Order.objects.filter(user = request.user, ordered = True).order_by('-id')
    context = {
        'purchase_orders' :purchase_orders,
    }
    return render(request, 'dashboard/purchase_orders.html', context)

# @login_required
# def sales_orders(request):
#     sales_items = OrderItem.objects.filter(user=request.user, ordered=True)
#     context = {
#         'sales_items':sales_items,
#     }
#     return render(request, 'dashboard/sales_orders.html', context)

@login_required 
def sales_orders(request):
    sales_orders = OrderItem.objects.filter(ordered=True, item__created_by=request.user).order_by('-id')
    context = {
        'sales_orders':sales_orders,
    }
    return render(request, 'dashboard/sales_orders.html', context) 

puddle/dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<body>
    {% include 'dashboard/topside.html' %}
    <!--Graphs-->
    <div class="container mx-auto sm:px-4">
        <div class="flex flex-wrap  my-5">
            <div class="md:w-1/2 pr-4 pl-4">
                <div class="bg-white">
                    <canvas id="myChart1" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart1').getContext('2d');
                        var myChart1 = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: [{% for item,quantity_sold in item_quantity_list %} '{{item.name}}',{% endfor %}],
                                datasets: [{
                                    label: 'Products',
                                    data: [{% for item,quantity_sold in item_quantity_list %} '{{item.quantity_sold}}',{% endfor %}],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
            {% comment %} <div class="md:w-1/2 pr-4 pl-4">
                <div class="bg-white">
                    <canvas id="myChart" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart').getContext('2d');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for date,total_income in date_income_list %} '{{date}}',{% endfor %}],
                                datasets: [{
                                    label: ['Products'],
                                    data: [{% for date,total_income in date_income_list %} '{{total_income}}',{% endfor %}],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div> {% endcomment %}
        </div>
    </div>
    <!--End Graphs-->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>
{% endblock content %}

puddle/dashboard/templates/dashboard/purchase_orders.html
{% extends 'core/base.html' %}

{% block title %}Orders{% endblock title %}

{% block content %}
{% include 'dashboard/topside.html' %}
<div class="flex flex-col overflow-x-auto  border-t-2 border-orange-600 mt-4">
    <div class="sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-x-auto">
          <table class="min-w-full text-center text-sm font-light">
            <thead class="border-b font-medium dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4 text-xl">Order_ID</th>
                <th scope="col" class="px-6 py-4 text-xl">Odered_date</th>
                <th scope="col" class="px-6 py-4 text-xl">Item Name</th>
                <th scope="col" class="px-6 py-4 text-xl">Price</th>
                <th scope="col" class="px-6 py-4 text-xl">Quantity</th>
                <th scope="col" class="px-6 py-4 text-xl">Total Item Price</th>
              </tr>
            </thead>
            <tbody>
            {% for purchase_order in purchase_orders %}
                {% for order_item in purchase_order.items.all %}
                    <tr class="border-b dark:border-neutral-500">
                        <td class="whitespace-nowrap px-6 py-4 font-bold">{{purchase_order.pk}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{purchase_order.ordered_date}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{order_item.item.name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{order_item.item.price}}</td>
                        <td class="whitespace-nowrap px-6 py-4">
                            {{order_item.quantity}}
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">
                            {% if order_item.item.discount_price %}
                                ${{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                                ${{ order_item.get_total_item_price }}
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                {% endfor %}
                {% if purchase_order.coupon %}
                <tr>
                    <td colspan="4"><b>Coupon</b></td>
                    <td><b>-${{ purchase_order.coupon.amount }}</b></td>
                </tr>
                {% endif %}
                {% if purchase_order.get_total %}
                <tr>
                        <td colspan="4"><b class="text-xl">Order Total</b></td>
                        <td><b class="text-xl">${{ purchase_order.get_total }}</b></td>
                </tr>
                {% endif %}
                <tr class="border-b border-orange-600">
                    <td class="py-4"></td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

puddle/dashboard/templates/dashboard/sales_orders.html
{% extends 'core/base.html' %}

{% block title %}Orders{% endblock title %}

{% block content %}
{% include 'dashboard/topside.html' %}
<div class="flex flex-col overflow-x-auto  border-t-2 border-orange-600 mt-4">
    <div class="sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-x-auto">
          <table class="min-w-full text-center text-sm font-light">
            <thead class="border-b font-medium dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4 text-xl">Order_ID</th>
                <th scope="col" class="px-6 py-4 text-xl">Odered_date</th>
                <th scope="col" class="px-6 py-4 text-xl">Item Name</th>
                <th scope="col" class="px-6 py-4 text-xl">Price</th>
                <th scope="col" class="px-6 py-4 text-xl">Quantity</th>
                <th scope="col" class="px-6 py-4 text-xl">Total Item Price</th>
              </tr>
            </thead>
            <tbody>
                {% for order_item in sales_orders %}
                    <tr class="border-b dark:border-neutral-500">
                        <td class="whitespace-nowrap px-6 py-4 font-bold">{{order_item.order_set.first.pk}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{order_item.order_set.first.start_date}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{order_item.item.name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{order_item.item.price}}</td>
                        <td class="whitespace-nowrap px-6 py-4">
                            {{order_item.quantity}}
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">
                            {% if order_item.item.discount_price %}
                                ${{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                                ${{ order_item.get_total_item_price }}
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                {% endfor %}
                {% comment %} {% if sales_order.coupon %}
                <tr>
                    <td colspan="4"><b>Coupon</b></td>
                    <td><b>-${{ sales_order.coupon.amount }}</b></td>
                </tr>
                {% endif %}
                {% if sales_order.get_total %}
                <tr>
                        <td colspan="4"><b class="text-xl">Order Total</b></td>
                        <td><b class="text-xl">${{ sales_order.get_total }}</b></td>
                </tr>
                {% endif %} {% endcomment %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

puddle/dashboard/templates/dashboard/topside.html
<head>
    {% comment %} <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> {% endcomment %}

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

    {% comment %} <!--Custome CSS-->
    <link rel="stylesheet" href="./style.css"> {% endcomment %}

   
</head>
   <!--Topside-->
   <div class="container mx-auto sm:px-4">
    <div class="flex flex-wrap  mt-4">
        <div class="md:w-1/3 pr-4 pl-4">
            <div class="relative flex flex-col min-w-0 rounded break-words border bg-white border-1 border-gray-300">
                <div class="py-3 px-6 mb-0 bg-gray-200 border-b-1 border-gray-300 text-gray-900 bg-orange-500 text-white">
                    Information
                </div>
                <div class="flex-auto p-6">
                    <marquee behavior="" direction="">
                        <h3 class="my-4">This is the Information</h3>
                    </marquee>
                </div>
            </div>
        </div>
        <div class="md:w-2/3 pr-4 pl-4">
            <div class="relative flex flex-col min-w-0 rounded break-words border bg-white border-1 border-gray-300">
                <div class="py-3 px-6 mb-0 bg-gray-200 border-b-1 border-gray-300 text-gray-900 bg-orange-500 text-white">
                    Statistics
                </div>
                <div class="flex-auto p-6">
                    <div class="flex flex-wrap ">
                        <div class="md:w-1/3 pr-4 pl-4">
                            <a class="text-decoration-none text-gray-900" href="{%url 'dashboard:index'%}">
                                <div class="relative flex flex-col min-w-0 rounded break-words border bg-white border-1 border-gray-300 my-card shadow text-center p-6">
                                    <h4>Dashboard<i class="fas fa-users"></i></h4>
                                    {% comment %} <h3>2</h3> {% endcomment %}
                                </div>
                            </a>
                        </div>
                        <div class="md:w-1/3 pr-4 pl-4">
                            <a class="text-decoration-none text-gray-900" href="{%url 'dashboard:purchase_orders'%}">
                                <div class="relative flex flex-col min-w-0 rounded break-words border bg-white border-1 border-gray-300 my-card shadow text-center p-6">
                                    <h4>Purchase Orders <i class="fas fa-box"></i></h4>
                                    {% comment %} <h3>4</h3> {% endcomment %}
                                </div>
                            </a>
                        </div>
                        <div class="md:w-1/3 pr-4 pl-4">
                            <a class="text-decoration-none text-gray-900" href="{%url 'dashboard:sales_orders'%}">
                                <div class="relative flex flex-col min-w-0 rounded break-words border bg-white border-1 border-gray-300 my-card shadow text-center p-6">
                                    <h4>Sales Orders <i class="fas fa-shipping-fast"></i></h4>
                                    {% comment %} <h3>4</h3> {% endcomment %}
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Topside-->