puddle/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('', views.inbox1, name='inbox1'),
    path('<int:pk>/', views.inbox, name='inbox'),
    # path('<int:pk>/', views.detail, name='detail')
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/index.html'), name='logout'),
    path('settings/', views.settings, name='settings'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:pk>/', views.profile, name='profile')
]

puddle/item/urls.py
from django.urls import path

from . import views
from .views import(
    OrderSummaryView
)

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<int:pk>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
]

puddle/payment/urls.py
from django.urls import path
from . import views

app_name='payment'

urlpatterns = [
    path('checkout/<int:pk>/',views.checkout, name='checkout'),
    path('process/<int:pk>/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from core.views import index

urlpatterns = [
    path("", include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('payment/',include('payment.urls')),
    path('rating/', include('rating.urls')),
    path('searchbyimage/', include('searchbyimage.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from payment.models import ShippingAddress
from django.utils import timezone
from django.db.models import Sum


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_add_to_cart_url(self):
        return reverse("item:add-to-cart", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("item:remove-from-cart", kwargs={
            'pk': self.pk
        })
    def get_orderitem_quantity(self):
        total_quantity = OrderItem.objects.filter(item_id=self.id, ordered=True).aggregate(Sum('quantity'))['quantity__sum']
        return total_quantity if total_quantity else 0
    
    def calculate_avg_rating(self):
        from rating.models import Rating
        ratings = Rating.objects.filter(item=self)
        if ratings.count() > 0:
            sum_ratings = sum([rating.rating for rating in ratings])
            self.average_rating = sum_ratings / ratings.count()
        else:
            self.average_rating = 0
        self.save()
    
    
class OrderItem(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    rated = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    


class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def __init__(self, *args, **kwargs):
        ordered_date = kwargs.pop('ordered_date', None)
        super().__init__(*args, **kwargs)
        self.ordered_date = ordered_date
        self.save()

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total
    
    def complete_order(self):
        # Set ordered to True for all order items in this order
        for item in self.items.all():
            item.ordered = True
            item.save()
        self.ordered = True
        self.ordered_date = timezone.now()
        self.save()


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

puddle/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description','price','image')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description','price','image','is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

puddle/item/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Category, OrderItem, Order
from django.contrib.auth.decorators import login_required
from django.db.models import Q, CharField, Value
from django.contrib import messages
from django.utils import timezone
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from unidecode import unidecode
from django.core.paginator import Paginator

from .forms import NewItemForm, EditItemForm
# Create your views here.

def items(request):
    items = Item.objects.filter(is_sold = False).order_by('-id')
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()

    if category_id and category_id != 0:
        items = items.filter(category_id=category_id)

    if query:
        # bỏ qua dấu và chuyển đổi chuỗi tìm kiếm sang chữ thường
        query1 = unidecode(query).lower()

        # lọc lại kết quả
        results = []
        for item in items:
            # bỏ qua dấu và chuyển đổi chuỗi name và description sang chữ thường
            name = unidecode(item.name).lower()
            description = unidecode(item.description).lower()

            if query1 in name or query in description:
                results.append(item)
        items = results
    
    paginator = Paginator(items, 9)  # Chia các mục thành các trang chứa tối đa 9 mục.

    page = request.GET.get('page')  # Lấy số trang từ tham số truy vấn.
    items = paginator.get_page(page)  # Lấy các mục cho trang hiện tại.

    numbers = [0.5,1.5,2.5,3.5,4.5]

    return render(request, 'item/items.html', {
        'items' : items,
        'query' : query,
        'categories': categories,
        'category_id': int(category_id),
        'numbers':numbers,
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    #number of start
    numbers = [0.5,1.5,2.5,3.5,4.5]
    return render(request, 'item/detail.html',{
        'item' : item,
        'related_items' : related_items,
        'numbers': numbers,

    })

@login_required
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form' : form,
        'title' : 'New Item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('core:profile', pk=request.user.username)

@login_required
def edit(request, pk):
    item =get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method== 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    return render(request, 'item/form.html',{
        'form': form,
        'title' : 'Edit Form'
    })

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("item:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("item:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("item:order-summary")


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("item:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("item:order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("item:order-summary")


@login_required
def remove_single_item_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("item:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("item:detail", pk=pk)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("item:detail", pk=pk)

# class OrderSummaryView(View):
#     def get(self,*args, **kwargs ):
#         return render(self.request, 'item/order_summary.html')
class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'item/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{item.name}} {%endblock%}

{%block content%}
    
    <div class="container mx-auto px-6 border">
        <div class="md:flex md:items-center w-2/3 mx-auto">
            <div class="md:w-1/2 lg:h-96 flex justify-center items-center bg-gray-100">
                <img class="rounded-xl object-cover h-full" src="{{item.image.url}}" alt="{{item.name}}">
            </div>
            <div class="w-full max-w-lg mx-auto mt-5 md:ml-8 md:mt-0 md:w-1/2">
                <h3 class="text-gray-700 uppercase text-lg">{{item.name}}</h3>
                {% if item.discount_price %}
                    <span class="text-gray-500 mt-2 mr-2 text-red-500"><del>{{item.price}}</del></span>
                    <span class="text-gray-500 mt-2">{{item.discount_price}}</span>
                {% else %}
                    <span class="text-gray-500 mt-2">{{item.price}} vnd</span>
                {% endif %}
                <p class="text-gray-500"><strong>Seller: </strong> <a href="{% url 'core:profile' item.created_by.username %}" class="text-decoration-line: underline">{{item.created_by.username}}</a> </p>
                {%if item.description%}
                    <p class="text-gray-500"><strong>Description: </strong> {{item.description}} </p>
                {% endif %}
                <!-- Rating -->
                <span class="flex items-center gap-4 text-sm rounded text-slate-500">
                <span class="flex gap-1 text-amber-400" role="img" aria-label="Rating: 4 out of 5 stars">
                {% for i in numbers %}
                    {% if i <= item.average_rating %}
                    <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                          <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                        </svg>
                      </span>
                      {% else %}
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                        </svg>
                      </span>
                      {% endif %}
                {% endfor %}
                    </span>
                    <span> {{item.average_rating}} out 5</span>
                </span>
                {% comment %} <span class="flex items-center gap-4 text-sm rounded text-slate-500">
                    <span class="flex gap-1 text-amber-400" role="img" aria-label="Rating: 4 out of 5 stars">
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                          <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                        </svg>
                      </span>
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                          <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                        </svg>
                      </span>
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                          <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                        </svg>
                      </span>
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                          <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                        </svg>
                      </span>
                      <span aria-hidden="true">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                        </svg>
                      </span>
                    </span>
                    <span>4.1 out 5</span>
                  </span> {% endcomment %}
                <hr class="my-3">
   
                {% if request.user == item.created_by %}
                    <div class="bg-white rounded-xl">
                        <p class="my-6">This is your item </p>
                        <a href="{% url 'item:edit' item.id %}" class="px-4 py-2 mx-2 bg-teal-600 text-white text-sm font-medium rounded hover:bg-teal-400 focus:outline-none focus:bg-indigo-500">Edit</a>
                        <a href="{% url 'item:delete' item.id %}" class="px-4 py-2 mx-2 bg-red-600 text-white text-sm font-medium rounded hover:bg-red-400 focus:outline-none focus:bg-indigo-500">Delete</a>
                    </div>
                {% else %}
                    <div class="flex items-center mt-6">
                        <a href="{{ item.get_add_to_cart_url }}" class="px-4 py-2 mx-2 bg-indigo-600 text-white text-sm font-medium rounded hover:bg-indigo-400 focus:outline-none focus:bg-indigo-500">Order Now</a>
                        <a href="{%url 'conversation:new' item.id%}" class="px-4 py-2 mx-2 bg-teal-600 text-white text-sm font-medium rounded hover:bg-teal-400 focus:outline-none focus:bg-indigo-500">Contact Seller</a>
                        <a href="{{ item.get_add_to_cart_url }}" class="mx-2 text-gray-600 border rounded-md p-2 hover:bg-gray-200 focus:outline-none">
                            <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                        </a>
                        <a href="{{ item.get_remove_from_cart_url }}">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                              class="mr-2 h-8 w-10 bg-blue-500">
                              <path
                                d="M3.375 3C2.339 3 1.5 3.84 1.5 4.875v.75c0 1.036.84 1.875 1.875 1.875h17.25c1.035 0 1.875-.84 1.875-1.875v-.75C22.5 3.839 21.66 3 20.625 3H3.375z" />
                              <path
                                fill-rule="evenodd"
                                d="M3.087 9l.54 9.176A3 3 0 006.62 21h10.757a3 3 0 002.995-2.824L20.913 9H3.087zm6.163 3.75A.75.75 0 0110 12h4a.75.75 0 010 1.5h-4a.75.75 0 01-.75-.75z"
                                clip-rule="evenodd" />
                            </svg>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="mt-16">
            <h3 class="text-gray-600 text-2xl font-medium">More Products</h3>
            <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-6">
                {% for item in related_items %}
                    <a href="{% url 'item:detail' item.id %}"> 
                        <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                            <div class="flex items-end justify-end h-56 w-full bg-cover" style="background-image: url('{{item.image.url}}')">
                                <button class="p-2 rounded-full bg-blue-600 text-white mx-5 -mb-4 hover:bg-blue-500 focus:outline-none focus:bg-blue-500">
                                    <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                                </button>
                            </div>
                            <div class="px-5 py-3">
                                <h3 class="text-gray-700 uppercase">{{item.name}}</h3>
                                {% if item.discount_price %}
                                    <span class="text-gray-500 mt-2">{{item.discount_price}}</span>
                                {% else %}
                                    <span class="text-gray-500 mt-2">{{item.price}}</span>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{%endblock%}

puddle/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %} {{title}} {% endblock title %} {{title}}

{% block content %}
<div class="w-2/3 flex justify-center">
<h1 class="mb-6 mr-8 text-3xl">{{title}}</h1>
<form method="post" action="." enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="space-y-4">
        {{form.as_p}}
        <img id="preview-image" src="#" alt="Preview" style="display: none; width: 200px; height: 200px;">
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-300 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
        {{form.non_field_errors}}
    </div>
    {% endif %}
    
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
</div>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('preview-image');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }

    document.getElementById('id_image').addEventListener('change', previewImage);
</script>
{% endblock content %}